### ISSUE TITLE
IPv6 cannot search database

### ISSUE THREAD

**Issue by mathgeek12** [roniemartinez/IPToCC#1]
I am a bit of a newbie, but while working on a geoip script, I was using this package.  Everytime I would try an IPv6 address I would get the same error.   

> AddressValueError: '2001:200::/35' (len 13 != 16) is not permitted as an IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?

 After tracing back the errors, I found that once determind it is an IPv6 address, it is searching the database for a string, when the IPv6 has already been converted to unicode in the function get_country_code.
![iptoccupdate](https://user-images.githubusercontent.com/36207893/40383310-957098be-5dce-11e8-9d8b-aedcbe8e84cd.png)

**Comment by roniemartinez** [comment]
Hi @mathgeek12 

You shouldn't call `ipv6_get_country_code()` directly as it was designed to accept `ipaddress.IPv6Address` type.

Instead, call [`get_country_code()`](https://github.com/Code-ReaQtor/IPToCC/blob/de72e5338042c40808d24bd1b6b5eb2e86f0d4b3/iptocc/__init__.py#L65) as conversions happen here.

Notice the source:
```python
    if six.PY2 and isinstance(ip_address, six.string_types):
        ip_address = ipaddress.ip_address(unicode(ip_address))
```

**Comment by mathgeek12** [comment]
@code-reaQtor Yes , i called the get_country_code. The issue is once it is directed to ipv6_get_country_code.  The string is already in Unicode but it is now looking for a string ‘{}/{}’ it is throwing that error because it is not searching for Unicode.  No matter the IPv6 address entered the error message always refers to “2001:200::/35” *after looking in the database this is the first ipv6 value listed. Once I edited that part of the ipv6 function , get_country_code was able to search the dB for ipv6 locations.
